using System.Collections.Generic;
using System.Text;
using UiharuMind.Localization.Generator.Model;

namespace UiharuMind.Localization.Generator.Emit;

/// <summary>
/// 强类型 key 枚举发射器。把默认文化的 key 集合按 identity mapping 拍平成
/// <c>public enum LangKey</c>：成员名即资源 key（ToString() 即可回查运行时）。
/// XAML 端靠 Avalonia 编译期 string→enum 转换拿到类型检查，因此无需 x:Static 嵌套。
/// </summary>
internal static class LangKeyEmitter
{
    internal static string Emit(
        string rootNamespace,
        string typeName,
        string sourcePath,
        IReadOnlyList<ResourceKeyValue> keys)
    {
        var builder = new StringBuilder(1024);
        builder.AppendLine("//------------------------------------------------------------------------------");
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("//     This code was generated by UiharuMind.Localization.Generator. Do not edit.");
        builder.AppendLine($"//     Key 来源: {sourcePath}");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine("//------------------------------------------------------------------------------");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 语言资源 key 的强类型枚举（identity mapping：成员名即资源 key，ToString() 即可回查）。");
        builder.AppendLine("/// XAML 用法: <c>{loc:Loc SettingsWindowTitle}</c>（编译期 string→enum 校验）");
        builder.AppendLine("/// C# 用法:   <c>LocalizationManager.Instance.GetString(LangKey.SettingsWindowTitle)</c>");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"public enum {typeName}");
        builder.AppendLine("{");

        foreach (var kv in keys)
        {
            builder.Append("    ");
            builder.Append(kv.Key);
            builder.AppendLine(",");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }
}