using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using UiharuMind.Localization.Generator.Model;

namespace UiharuMind.Localization.Generator.Emit;

/// <summary>
/// 强类型 key 枚举发射器。把默认文化的 key 集合按 identity mapping 拍平成
/// <c>public enum LangKey</c>：成员名即资源 key（ToString() 即可回查运行时）。
/// XAML 端靠 Avalonia 编译期 string→enum 转换拿到类型检查，因此无需 x:Static 嵌套。
/// </summary>
internal static class LangKeyEmitter
{
    internal static string Emit(
        string rootNamespace,
        string typeName,
        string sourcePath,
        IReadOnlyList<ResourceKeyValue> keys)
    {
        var builder = new StringBuilder(1024);
        builder.AppendLine("//------------------------------------------------------------------------------");
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("//     This code was generated by UiharuMind.Localization.Generator. Do not edit.");
        builder.AppendLine($"//     Key 来源: {sourcePath}");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine("//------------------------------------------------------------------------------");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// 语言资源 key 的强类型枚举（identity mapping：成员名即资源 key，ToString() 即可回查）。");
        builder.AppendLine("/// XAML 用法: <c>{loc:Loc SettingsWindowTitle}</c>（编译期 string→enum 校验）");
        builder.AppendLine("/// C# 用法:   <c>LocalizationManager.Instance.GetString(LangKey.SettingsWindowTitle)</c>");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"public enum {typeName}");
        builder.AppendLine("{");

        foreach (var kv in keys)
        {
            if (!string.IsNullOrWhiteSpace(kv.Value))
            {
                builder.Append("    /// <summary>");
                builder.Append(EscapeForDocComment(kv.Value));
                builder.AppendLine("</summary>");
            }

            builder.Append("    ");
            builder.Append(kv.Key);
            builder.AppendLine(",");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// 把默认文案转成可安全放进 <c>///</c> 行注释的文本：
    /// Trim → 控制字符（含换行/制表）替换为空格 → 连续空白折叠为单个空格 → XML 转义。
    /// 必须保证结果不含原始换行/控制字符，否则行注释被截断、后续文案变成代码直接编译失败。
    /// </summary>
    private static string EscapeForDocComment(string value)
    {
        var trimmed = value.Trim();
        var builder = new StringBuilder(trimmed.Length);
        foreach (var c in trimmed)
        {
            builder.Append(char.IsControl(c) ? ' ' : c);
        }

        var collapsed = Regex.Replace(builder.ToString(), @"\s+", " ").Trim();
        return collapsed
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}