using System.Collections.ObjectModel;
using Microsoft.Extensions.AI;
using SkiaSharp;
using UiharuMind.App.Tests.TestDoubles;
using UiharuMind.Core.AI.Chat;
using UiharuMind.Core.AI.Execution;
using UiharuMind.Core.AI.Execution.Files;
using UiharuMind.Features.Conversation;
using UiharuMind.Features.Conversation.Items;

namespace UiharuMind.App.Tests.Headless;

/// <summary>
/// 切回会话时回放出来的生图卡片也要有图：结果里是草稿目录简写，回放得按会话口径展开，
/// 不能只有实时那一路认得
/// </summary>
[Collection(HeadlessCollection.Name)]
public sealed class HistoryReplayResultImagesTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "uiharu-replay-images-" + Guid.NewGuid().ToString("N"));

    private sealed class StubHost : IConversationItemActionHost
    {
        public ChatSession? Session => null;
        public bool IsGenerating => false;
        public void Rerun(ChatMessage? input) { }
        public void NotifySessionsChanged() { }
        public void NotifyItemsWired() { }
    }

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
    }

    [Fact]
    public void ReplayedGenerateImageCard_LoadsItsThumbnailFromDraftShorthand() => HeadlessUi.Run(() =>
    {
        string draft = Path.Combine(_root, "draft");
        Directory.CreateDirectory(Path.Combine(draft, "images"));
        using (SKBitmap bitmap = new(64, 64))
        using (SKData data = bitmap.Encode(SKEncodedImageFormat.Png, 100))
        {
            File.WriteAllBytes(Path.Combine(draft, "images", "fox.png"), data.ToArray());
        }

        ObservableCollection<ConversationItemBase> items = new();
        ConversationHistoryRenderer renderer = new(items,
            new ConversationItemActions(items, new StubHost(), new RecordingMessageService()),
            () => null, () => false, () => null, () => new AgentPathResolver(null, draft));
        List<ChatMessage> history =
        [
            new(ChatRole.User, "画只狐狸"),
            new(ChatRole.Assistant, [new FunctionCallContent("c1", ImageGenerationTool.ToolName)]),
            new(ChatRole.Tool, [new FunctionResultContent("c1", "Generated by m.\nSaved: $DRAFT/images/fox.png")]),
        ];

        List<ConversationItemBase> built = renderer.Build(history, 0, history.Count);

        ToolCallItem card = Assert.Single(built.OfType<ToolCallItem>());
        Assert.True(card.HasResultImages);
    });
}
