using SkiaSharp;
using UiharuMind.Core.AI.Execution;
using UiharuMind.Core.AI.Execution.Files;
using UiharuMind.Features.Conversation.Items;

namespace UiharuMind.App.Tests.Headless;

/// <summary>
/// 生图与看图卡片的缩略图：结果里的草稿目录简写按会话口径展开、只解缩略图大小、丢弃条目时释放
/// </summary>
[Collection(HeadlessCollection.Name)]
public sealed class ToolCallResultImagesTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "uiharu-tool-images-" + Guid.NewGuid().ToString("N"));

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
    }

    private AgentPathResolver Paths => new(Path.Combine(_root, "workspace"), Path.Combine(_root, "draft"));

    private void WritePng(string relativePath, int width, int height)
    {
        string path = Path.Combine(_root, "draft", relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        using SKBitmap bitmap = new(width, height);
        using SKData data = bitmap.Encode(SKEncodedImageFormat.Png, 100);
        File.WriteAllBytes(path, data.ToArray());
    }

    private static ToolCallItem Finished(string toolName, string result) => new()
    {
        ToolName = toolName, IsRunning = false, IsSuccess = true, ResultText = result,
    };

    [Fact]
    public void GeneratedImage_LoadsAsThumbnailFromDraftShorthand() => HeadlessUi.RunAsync(async () =>
    {
        WritePng("images/fox.png", 1280, 960);
        ToolCallItem item = Finished(ImageGenerationTool.ToolName,
            "Generated by m.\nSaved: $DRAFT/images/fox.png\nThe image is already shown to the user.");

        await item.LoadResultImagesAsync(Paths);

        ToolResultImage image = Assert.Single(item.ResultImages);
        Assert.Equal(320, image.Thumbnail.PixelSize.Width);
        Assert.Equal(Path.Combine(_root, "draft", "images", "fox.png"), image.FilePath);

        item.ReleaseImages();
        Assert.False(item.HasResultImages);
    });

    /// <summary>ViewImage 的卡片显示模型看到的那份预览（ADR 0053）</summary>
    [Fact]
    public void ViewedImage_ShowsThePreviewTheModelSaw() => HeadlessUi.RunAsync(async () =>
    {
        WritePng("images/previews/ab12.png", 640, 480);
        ToolCallItem item = Finished(ViewImageTool.ToolName,
            "Attached: cat.png\nPreview: $DRAFT/images/previews/ab12.png\nThe images follow in the next message.");

        await item.LoadResultImagesAsync(Paths);

        Assert.Equal(Path.Combine(_root, "draft", "images", "previews", "ab12.png"),
            Assert.Single(item.ResultImages).FilePath);
    });

    /// <summary>解码在后台：条目在解完之前就被裁掉（释放），晚到的图不能再挂上去</summary>
    [Fact]
    public void ReleasedBeforeDecodeFinishes_DropsTheLateThumbnail() => HeadlessUi.RunAsync(async () =>
    {
        WritePng("images/fox.png", 640, 480);
        ToolCallItem item = Finished(ImageGenerationTool.ToolName, "Saved: $DRAFT/images/fox.png");

        Task loading = item.LoadResultImagesAsync(Paths);
        item.ReleaseImages();
        await loading;

        Assert.False(item.HasResultImages);
    });

    [Fact]
    public void DeletedFileOrOtherTool_ShowsNothing() => HeadlessUi.RunAsync(async () =>
    {
        WritePng("images/fox.png", 64, 64);
        ToolCallItem missing = Finished(ImageGenerationTool.ToolName, "Saved: $DRAFT/images/gone.png");
        ToolCallItem otherTool = Finished("Read", "Saved: $DRAFT/images/fox.png");

        await missing.LoadResultImagesAsync(Paths);
        await otherTool.LoadResultImagesAsync(Paths);

        Assert.False(missing.HasResultImages);
        Assert.False(otherTool.HasResultImages);
    });
}
