using Microsoft.Extensions.AI;
using UiharuMind.Core.AI.Execution;

namespace UiharuMind.Core.Tests.Execution;

/// <summary>
/// 生图计数：只数生图调用成功存下的图。按张计费，数错了用量面板上那一行就是假的
/// </summary>
public class GeneratedImageTallyTests
{
    private static FunctionCallContent Call(string callId, string name) => new(callId, name);

    private static FunctionResultContent Result(string callId, string text) => new(callId, text);

    [Fact]
    public void SavedImages_AreCounted()
    {
        GeneratedImageTally tally = new();

        Assert.Equal(0, tally.Observe(Call("c1", ImageGenerationTool.ToolName)));
        int count = tally.Observe(Result("c1",
            "Generated by m.\nSaved: $DRAFT/images/a.png\nSaved: $DRAFT/images/b.png\nThe image is already shown."));

        Assert.Equal(2, count);
    }

    [Fact]
    public void FailedGeneration_CountsNothing()
    {
        GeneratedImageTally tally = new();
        tally.Observe(Call("c1", ImageGenerationTool.ToolName));

        Assert.Equal(0, tally.Observe(Result("c1", "Error: prompt must not be empty.")));
    }

    /// <summary>别的工具的结果里恰好有一行 Saved: 也不算</summary>
    [Fact]
    public void OtherToolResult_IsIgnored()
    {
        GeneratedImageTally tally = new();
        tally.Observe(Call("c1", "Write"));

        Assert.Equal(0, tally.Observe(Result("c1", "Saved: notes.md")));
    }

    /// <summary>同一个结果再来一遍（流里重放、观察者补发）不重复计</summary>
    [Fact]
    public void SameResultTwice_CountsOnce()
    {
        GeneratedImageTally tally = new();
        tally.Observe(Call("c1", ImageGenerationTool.ToolName));
        FunctionResultContent result = Result("c1", "Saved: $DRAFT/images/a.png");

        Assert.Equal(1, tally.Observe(result));
        Assert.Equal(0, tally.Observe(result));
    }
}
