using System.Text.Json;
using Microsoft.Extensions.AI;
using UiharuMind.Core.AI.Character;
using UiharuMind.Core.AI.Execution;
using UiharuMind.Core.AI.Execution.Assembly;
using UiharuMind.Core.AI.Execution.Files;
using UiharuMind.Core.AI.ImageGeneration;
using UiharuMind.Core.AI.ImageGeneration.Dialects;
using UiharuMind.Core.Tests.Utils;

namespace UiharuMind.Core.Tests.Execution;

/// <summary>
/// GenerateImage 的工具侧：入参校验、产出落进草稿目录、结果只给路径、失败按类给「此刻该怎么办」。
/// 回退链本身见 ImageGenerationServiceTests
/// </summary>
public sealed class ImageGenerationToolTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "uiharu-imagegen-" + Guid.NewGuid().ToString("N"));

    private sealed class RecordingDialect(ImageOutcome outcome) : IImageDialect
    {
        public ImageRequest? LastRequest { get; private set; }

        public Task<ImageOutcome> GenerateAsync(ImageModelInfo model, ImageRequest request, CancellationToken ct)
        {
            LastRequest = request;
            return Task.FromResult(outcome);
        }
    }

    private string Workspace => Path.Combine(_root, "workspace");

    private string Draft => Path.Combine(_root, "draft");

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
    }

    private async Task<string> Invoke(RecordingDialect dialect, string prompt, string[]? images = null,
        string? aspectRatio = null)
    {
        Directory.CreateDirectory(Workspace);
        ImageModelInfo model = new() { Name = "painter", Endpoint = "https://example.com/v1", ModelId = "x" };
        ImageGenerationService service = new(() => [model], _ => dialect, (_, _) => Task.FromResult(TestImages.Png(1, 1)));
        AIFunction tool = (AIFunction)ImageGenerationTool.Create(new AgentPathResolver(Workspace, Draft), service);

        object? raw = await tool.InvokeAsync(new AIFunctionArguments
        {
            ["prompt"] = prompt,
            ["images"] = images,
            ["aspectRatio"] = aspectRatio,
        }, TestContext.Current.CancellationToken);
        return raw is JsonElement { ValueKind: JsonValueKind.String } element
            ? element.GetString() ?? string.Empty
            : raw?.ToString() ?? string.Empty;
    }

    private static RecordingDialect Drawing() => new(new ImageOutcome { Images = [new ImageOutput(TestImages.Png(8, 8), null)] });

    [Fact]
    public async Task Success_SavesIntoDraftAndReturnsShorthandPath()
    {
        string result = await Invoke(Drawing(), "A red fox");

        string saved = Assert.Single(ImageGenerationTool.ParseSavedPaths(result));
        Assert.StartsWith("$DRAFT/images/", saved);
        Assert.EndsWith("-a-red-fox.png", saved);
        Assert.Single(Directory.GetFiles(Path.Combine(Draft, ImageGenerationTool.OutputFolder)));
        Assert.Contains("Generated by painter", result);
        Assert.DoesNotContain("file://", result); //图不进结果,完整路径也不进:贴图的前缀系统提示里有
    }

    [Fact]
    public async Task Edit_LoadsInputsInOrderAndSniffsTheirType()
    {
        Directory.CreateDirectory(Workspace);
        await File.WriteAllBytesAsync(Path.Combine(Workspace, "main.dat"), TestImages.Jpeg(4, 3), TestContext.Current.CancellationToken);
        await File.WriteAllBytesAsync(Path.Combine(Workspace, "ref.png"), TestImages.Png(2, 2), TestContext.Current.CancellationToken);
        RecordingDialect dialect = Drawing();

        await Invoke(dialect, "make it night", ["main.dat", "ref.png"], "16:9");

        ImageRequest request = dialect.LastRequest!;
        Assert.Equal(["image/jpeg", "image/png"], request.Images.Select(i => i.MediaType));
        Assert.Equal(new ImageAspectRatio(16, 9), request.AspectRatio);
    }

    [Fact]
    public async Task MissingAndNonImageInputs_AreRejectedBeforeAnyCall()
    {
        Directory.CreateDirectory(Workspace);
        await File.WriteAllTextAsync(Path.Combine(Workspace, "notes.txt"), "hello", TestContext.Current.CancellationToken);
        RecordingDialect dialect = Drawing();

        string missing = await Invoke(dialect, "x", ["nope.png"]);
        string notImage = await Invoke(dialect, "x", ["notes.txt"]);

        Assert.Contains("not found: nope.png", missing);
        Assert.Contains("not a PNG, JPEG or WebP image: notes.txt", notImage);
        Assert.Null(dialect.LastRequest);
    }

    [Theory]
    [InlineData("", null, "prompt must not be empty")]
    [InlineData("x", "21:9", "unsupported aspectRatio")]
    public async Task InvalidArguments_ExplainThemselves(string prompt, string? ratio, string expected)
    {
        Assert.Contains(expected, await Invoke(Drawing(), prompt, aspectRatio: ratio));
    }

    [Fact]
    public async Task TooManyImages_IsRejected()
    {
        string[] images = Enumerable.Range(0, ImageRequest.MaxImages + 1).Select(i => $"{i}.png").ToArray();

        Assert.Contains($"at most {ImageRequest.MaxImages}", await Invoke(Drawing(), "x", images));
    }

    [Fact]
    public async Task MaybeCharged_TellsTheModelNotToRetry()
    {
        string result = await Invoke(new RecordingDialect(ImageOutcome.Fail(EImageFailureKind.MaybeCharged, "timed out")), "x");

        Assert.Contains("do not retry on your own", result);
        Assert.Empty(ImageGenerationTool.ParseSavedPaths(result));
    }

    [Fact]
    public async Task Rejected_AsksForARevision()
    {
        string result = await Invoke(new RecordingDialect(ImageOutcome.Fail(EImageFailureKind.Rejected, "safety")), "x");

        Assert.Contains("Revise the prompt", result);
    }

    [Fact]
    public void ImagesDescription_StatesTheSameLimitAsTheRequest()
    {
        // 特性参数里插不了 int 常量,描述只能写字面量:这里钉住两边不走样
        AIFunction tool = (AIFunction)ImageGenerationTool.Create(new AgentPathResolver(Workspace, Draft));

        Assert.Contains($"at most {ImageRequest.MaxImages})", tool.JsonSchema.GetRawText());
    }

    [Theory]
    [InlineData("A cat, sitting on a mat!", "20261001-090807-a-cat-sitting-on-a-mat")]
    [InlineData("一只猫", "20261001-090807")]
    public void FileStem_KeepsAsciiWordsOnly(string prompt, string expected)
    {
        Assert.Equal(expected, ImageGenerationTool.BuildFileStem(prompt, new DateTime(2026, 10, 1, 9, 8, 7)));
    }

    [Theory]
    [InlineData(true, true, true, true)]
    [InlineData(true, true, false, false)] //没配生图模型:一个 token 都不占
    [InlineData(true, false, true, false)] //角色关掉了
    [InlineData(false, true, true, false)] //普通角色不装工具
    public void Mount_RequiresAgentToggleAndConfiguredModel(bool isAgent, bool enabled, bool configured, bool expected)
    {
        CharacterData character = new()
        {
            CharacterId = "a", IsAgent = isAgent, Tools = new AgentToolConfig { EnableImageGeneration = enabled },
        };
        AgentAssemblyPlan plan = new()
        {
            Profile = new AgentBuildProfile { Character = character }, ImageModelsConfigured = configured,
        };
        AgentAssemblyFacts facts = AgentAssemblyFacts.Capture(character,
            new AgentAssemblyInputs
            {
                Permission = EAgentPermissionMode.AutoEdit, ImageModelsConfigured = configured,
            });

        Assert.Equal(expected, plan.MountImageGeneration);
        Assert.Equal(expected, facts.ImageGeneration); //重建判据与挂载判据同一口径
    }
}
