//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiharuMind.Resources.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UiharuMind.Resources.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        public static string SendUserDesc {
            get {
                return ResourceManager.GetString("SendUserDesc", resourceCulture);
            }
        }
        
        public static string ChatInputTips {
            get {
                return ResourceManager.GetString("ChatInputTips", resourceCulture);
            }
        }
        
        public static string EjectModel {
            get {
                return ResourceManager.GetString("EjectModel", resourceCulture);
            }
        }
        
        public static string MessageInfoTitle {
            get {
                return ResourceManager.GetString("MessageInfoTitle", resourceCulture);
            }
        }
        
        public static string MessageErrorTitle {
            get {
                return ResourceManager.GetString("MessageErrorTitle", resourceCulture);
            }
        }
        
        public static string MenuMainKey {
            get {
                return ResourceManager.GetString("MenuMainKey", resourceCulture);
            }
        }
        
        public static string MenuModelKey {
            get {
                return ResourceManager.GetString("MenuModelKey", resourceCulture);
            }
        }
        
        public static string MenuChatKey {
            get {
                return ResourceManager.GetString("MenuChatKey", resourceCulture);
            }
        }
        
        public static string MenuTranslateKey {
            get {
                return ResourceManager.GetString("MenuTranslateKey", resourceCulture);
            }
        }
        
        public static string MenuLogKey {
            get {
                return ResourceManager.GetString("MenuLogKey", resourceCulture);
            }
        }
        
        public static string MenuSettingKey {
            get {
                return ResourceManager.GetString("MenuSettingKey", resourceCulture);
            }
        }
        
        public static string MenuAboutKey {
            get {
                return ResourceManager.GetString("MenuAboutKey", resourceCulture);
            }
        }
        
        public static string SettingDebug {
            get {
                return ResourceManager.GetString("SettingDebug", resourceCulture);
            }
        }
        
        public static string SettingLogDetail {
            get {
                return ResourceManager.GetString("SettingLogDetail", resourceCulture);
            }
        }
        
        public static string SettingLogEnable {
            get {
                return ResourceManager.GetString("SettingLogEnable", resourceCulture);
            }
        }
        
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string ConfirmDeleteRuntimeEngine {
            get {
                return ResourceManager.GetString("ConfirmDeleteRuntimeEngine", resourceCulture);
            }
        }
        
        public static string Decompressing {
            get {
                return ResourceManager.GetString("Decompressing", resourceCulture);
            }
        }
        
        public static string RuntimeEngineSetting {
            get {
                return ResourceManager.GetString("RuntimeEngineSetting", resourceCulture);
            }
        }
        
        public static string CurrentEngineTypeSetting {
            get {
                return ResourceManager.GetString("CurrentEngineTypeSetting", resourceCulture);
            }
        }
        
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        public static string LLamaCppSetting {
            get {
                return ResourceManager.GetString("LLamaCppSetting", resourceCulture);
            }
        }
        
        public static string InAnswer {
            get {
                return ResourceManager.GetString("InAnswer", resourceCulture);
            }
        }
        
        public static string Plaintext {
            get {
                return ResourceManager.GetString("Plaintext", resourceCulture);
            }
        }
        
        public static string ChatPlaintextTooltip {
            get {
                return ResourceManager.GetString("ChatPlaintextTooltip", resourceCulture);
            }
        }
        
        public static string ClipboardHistory {
            get {
                return ResourceManager.GetString("ClipboardHistory", resourceCulture);
            }
        }
        
        public static string CopiedToClipboardTips {
            get {
                return ResourceManager.GetString("CopiedToClipboardTips", resourceCulture);
            }
        }
        
        public static string ClipboardHistoryCount {
            get {
                return ResourceManager.GetString("ClipboardHistoryCount", resourceCulture);
            }
        }
        
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        public static string DeleteAllClipboardHistoryTips {
            get {
                return ResourceManager.GetString("DeleteAllClipboardHistoryTips", resourceCulture);
            }
        }
        
        public static string QuickChatQuateTitle {
            get {
                return ResourceManager.GetString("QuickChatQuateTitle", resourceCulture);
            }
        }
        
        public static string DefaultQuickChatTitle {
            get {
                return ResourceManager.GetString("DefaultQuickChatTitle", resourceCulture);
            }
        }
        
        public static string CreateRemoteModel {
            get {
                return ResourceManager.GetString("CreateRemoteModel", resourceCulture);
            }
        }
        
        public static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        public static string ModifyBtn {
            get {
                return ResourceManager.GetString("ModifyBtn", resourceCulture);
            }
        }
        
        public static string CreateBtn {
            get {
                return ResourceManager.GetString("CreateBtn", resourceCulture);
            }
        }
        
        public static string SureBtn {
            get {
                return ResourceManager.GetString("SureBtn", resourceCulture);
            }
        }
        
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        public static string CustomConfig {
            get {
                return ResourceManager.GetString("CustomConfig", resourceCulture);
            }
        }
        
        public static string NotInputModelNameTips {
            get {
                return ResourceManager.GetString("NotInputModelNameTips", resourceCulture);
            }
        }
        
        public static string NotInputModelApiKey {
            get {
                return ResourceManager.GetString("NotInputModelApiKey", resourceCulture);
            }
        }
        
        public static string ClearChatHistory {
            get {
                return ResourceManager.GetString("ClearChatHistory", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string CharacterDesc {
            get {
                return ResourceManager.GetString("CharacterDesc", resourceCulture);
            }
        }
        
        public static string CharacterFirstGreeting {
            get {
                return ResourceManager.GetString("CharacterFirstGreeting", resourceCulture);
            }
        }
        
        public static string CharacterDialogTemplate {
            get {
                return ResourceManager.GetString("CharacterDialogTemplate", resourceCulture);
            }
        }
        
        public static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        public static string ParameterSettings {
            get {
                return ResourceManager.GetString("ParameterSettings", resourceCulture);
            }
        }
        
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        public static string DeleteTips {
            get {
                return ResourceManager.GetString("DeleteTips", resourceCulture);
            }
        }
        
        public static string ClearTips {
            get {
                return ResourceManager.GetString("ClearTips", resourceCulture);
            }
        }
        
        public static string MountsTitle {
            get {
                return ResourceManager.GetString("MountsTitle", resourceCulture);
            }
        }
        
        public static string MountsDesc {
            get {
                return ResourceManager.GetString("MountsDesc", resourceCulture);
            }
        }
        
        public static string MountsNullTips {
            get {
                return ResourceManager.GetString("MountsNullTips", resourceCulture);
            }
        }
        
        public static string SystemPrompt {
            get {
                return ResourceManager.GetString("SystemPrompt", resourceCulture);
            }
        }
        
        public static string RoleplayCharacter {
            get {
                return ResourceManager.GetString("RoleplayCharacter", resourceCulture);
            }
        }
        
        public static string ToolCharacter {
            get {
                return ResourceManager.GetString("ToolCharacter", resourceCulture);
            }
        }
        
        public static string CharacterFuncType {
            get {
                return ResourceManager.GetString("CharacterFuncType", resourceCulture);
            }
        }
        
        public static string AddDuplicateCharacterTips {
            get {
                return ResourceManager.GetString("AddDuplicateCharacterTips", resourceCulture);
            }
        }
        
        public static string OptionalPromptParams {
            get {
                return ResourceManager.GetString("OptionalPromptParams", resourceCulture);
            }
        }
        
        public static string OptionalPromptParamsDesc {
            get {
                return ResourceManager.GetString("OptionalPromptParamsDesc", resourceCulture);
            }
        }
        
        public static string ToggleIsPhotoListView {
            get {
                return ResourceManager.GetString("ToggleIsPhotoListView", resourceCulture);
            }
        }
        
        public static string ToggleIsListView {
            get {
                return ResourceManager.GetString("ToggleIsListView", resourceCulture);
            }
        }
        
        public static string MessageWarningTitle {
            get {
                return ResourceManager.GetString("MessageWarningTitle", resourceCulture);
            }
        }
    }
}
