//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiharuMind.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiharuMind.Resources.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Character,Edit?.
        /// </summary>
        public static string AddDuplicateCharacterTips {
            get {
                return ResourceManager.GetString("AddDuplicateCharacterTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        public static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiKey.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        public static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Card.
        /// </summary>
        public static string CharacterCard {
            get {
                return ResourceManager.GetString("CharacterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CharacterCopyTips {
            get {
                return ResourceManager.GetString("CharacterCopyTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CharacterDeleteTips {
            get {
                return ResourceManager.GetString("CharacterDeleteTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Desciption.
        /// </summary>
        public static string CharacterDesc {
            get {
                return ResourceManager.GetString("CharacterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Template.
        /// </summary>
        public static string CharacterDialogTemplate {
            get {
                return ResourceManager.GetString("CharacterDialogTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Greeting.
        /// </summary>
        public static string CharacterFirstGreeting {
            get {
                return ResourceManager.GetString("CharacterFirstGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CharacterFuncType.
        /// </summary>
        public static string CharacterFuncType {
            get {
                return ResourceManager.GetString("CharacterFuncType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character User.
        /// </summary>
        public static string CharacterUser {
            get {
                return ResourceManager.GetString("CharacterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Enter.
        /// </summary>
        public static string ChatInputTips {
            get {
                return ResourceManager.GetString("ChatInputTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Markdown.
        /// </summary>
        public static string ChatPlaintextTooltip {
            get {
                return ResourceManager.GetString("ChatPlaintextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Chat History.
        /// </summary>
        public static string ClearChatHistory {
            get {
                return ResourceManager.GetString("ClearChatHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ClearTips {
            get {
                return ResourceManager.GetString("ClearTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard History.
        /// </summary>
        public static string ClipboardHistory {
            get {
                return ResourceManager.GetString("ClipboardHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count: {0}.
        /// </summary>
        public static string ClipboardHistoryCount {
            get {
                return ResourceManager.GetString("ClipboardHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ConfirmDeleteRuntimeEngine {
            get {
                return ResourceManager.GetString("ConfirmDeleteRuntimeEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertToTempChat.
        /// </summary>
        public static string ConvertToTempChat {
            get {
                return ResourceManager.GetString("ConvertToTempChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard!.
        /// </summary>
        public static string CopiedToClipboardTips {
            get {
                return ResourceManager.GetString("CopiedToClipboardTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateBtn {
            get {
                return ResourceManager.GetString("CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Remote Model：.
        /// </summary>
        public static string CreateRemoteModel {
            get {
                return ResourceManager.GetString("CreateRemoteModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Engine Type:.
        /// </summary>
        public static string CurrentEngineTypeSetting {
            get {
                return ResourceManager.GetString("CurrentEngineTypeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomConfig.
        /// </summary>
        public static string CustomConfig {
            get {
                return ResourceManager.GetString("CustomConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing.
        /// </summary>
        public static string Decompressing {
            get {
                return ResourceManager.GetString("Decompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string DefaultQuickChatTitle {
            get {
                return ResourceManager.GetString("DefaultQuickChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string DeleteAllClipboardHistoryTips {
            get {
                return ResourceManager.GetString("DeleteAllClipboardHistoryTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeleteCharacterTips {
            get {
                return ResourceManager.GetString("DeleteCharacterTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string DeleteTips {
            get {
                return ResourceManager.GetString("DeleteTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Character.
        /// </summary>
        public static string EditCharacter {
            get {
                return ResourceManager.GetString("EditCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject Model.
        /// </summary>
        public static string EjectModel {
            get {
                return ResourceManager.GetString("EjectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain.
        /// </summary>
        public static string Explain {
            get {
                return ResourceManager.GetString("Explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Request.
        /// </summary>
        public static string ExtraRequestText {
            get {
                return ResourceManager.GetString("ExtraRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Requirement for Translation.
        /// </summary>
        public static string ExtraRequestTextBoxTips {
            get {
                return ResourceManager.GetString("ExtraRequestTextBoxTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Answer....
        /// </summary>
        public static string InAnswer {
            get {
                return ResourceManager.GetString("InAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Not Take Histor yContext.
        /// </summary>
        public static string IsNotTakeHistoryContext {
            get {
                return ResourceManager.GetString("IsNotTakeHistoryContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLamaCpp Setting.
        /// </summary>
        public static string LLamaCppSetting {
            get {
                return ResourceManager.GetString("LLamaCppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAboutKey {
            get {
                return ResourceManager.GetString("MenuAboutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string MenuChatKey {
            get {
                return ResourceManager.GetString("MenuChatKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string MenuLogKey {
            get {
                return ResourceManager.GetString("MenuLogKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MenuMainKey {
            get {
                return ResourceManager.GetString("MenuMainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string MenuModelKey {
            get {
                return ResourceManager.GetString("MenuModelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string MenuSettingKey {
            get {
                return ResourceManager.GetString("MenuSettingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string MenuTranslateKey {
            get {
                return ResourceManager.GetString("MenuTranslateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageErrorTitle {
            get {
                return ResourceManager.GetString("MessageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MessageInfoTitle {
            get {
                return ResourceManager.GetString("MessageInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageWarningTitle {
            get {
                return ResourceManager.GetString("MessageWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ModifyBtn {
            get {
                return ResourceManager.GetString("ModifyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MountsDesc {
            get {
                return ResourceManager.GetString("MountsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        public static string MountsNullTips {
            get {
                return ResourceManager.GetString("MountsNullTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounts.
        /// </summary>
        public static string MountsTitle {
            get {
                return ResourceManager.GetString("MountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Api Key!.
        /// </summary>
        public static string NotInputModelApiKey {
            get {
                return ResourceManager.GetString("NotInputModelApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input Model Name!.
        /// </summary>
        public static string NotInputModelNameTips {
            get {
                return ResourceManager.GetString("NotInputModelNameTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Directory.
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Prompt Params.
        /// </summary>
        public static string OptionalPromptParams {
            get {
                return ResourceManager.GetString("OptionalPromptParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{$user}}：replace by username。{
        ///{$char}}：replace by character name.
        /// </summary>
        public static string OptionalPromptParamsDesc {
            get {
                return ResourceManager.GetString("OptionalPromptParamsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter settings.
        /// </summary>
        public static string ParameterSettings {
            get {
                return ResourceManager.GetString("ParameterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Params Lang($lang).
        /// </summary>
        public static string ParamsLang {
            get {
                return ResourceManager.GetString("ParamsLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaintext.
        /// </summary>
        public static string Plaintext {
            get {
                return ResourceManager.GetString("Plaintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quate：.
        /// </summary>
        public static string QuickChatQuateTitle {
            get {
                return ResourceManager.GetString("QuickChatQuateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate.
        /// </summary>
        public static string RegenerateBtn {
            get {
                return ResourceManager.GetString("RegenerateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleplayCharacter {
            get {
                return ResourceManager.GetString("RoleplayCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Engine Setting.
        /// </summary>
        public static string RuntimeEngineSetting {
            get {
                return ResourceManager.GetString("RuntimeEngineSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ScreenCapturePosition {
            get {
                return ResourceManager.GetString("ScreenCapturePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string ScreenCaptureResolution {
            get {
                return ResourceManager.GetString("ScreenCaptureResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendUserDesc {
            get {
                return ResourceManager.GetString("SendUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string SettingDebug {
            get {
                return ResourceManager.GetString("SettingDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set verbosity level to infinity (i.e. log all messages, useful for debugging)
        ///.
        /// </summary>
        public static string SettingLogDetail {
            get {
                return ResourceManager.GetString("SettingLogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable log messages.
        /// </summary>
        public static string SettingLogEnable {
            get {
                return ResourceManager.GetString("SettingLogEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Chat.
        /// </summary>
        public static string StartChat {
            get {
                return ResourceManager.GetString("StartChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure.
        /// </summary>
        public static string SureBtn {
            get {
                return ResourceManager.GetString("SureBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemPrompt.
        /// </summary>
        public static string SystemPrompt {
            get {
                return ResourceManager.GetString("SystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        public static string TargetLanguageText {
            get {
                return ResourceManager.GetString("TargetLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think.
        /// </summary>
        public static string Think {
            get {
                return ResourceManager.GetString("Think", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        public static string ToggleIsListView {
            get {
                return ResourceManager.GetString("ToggleIsListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo View.
        /// </summary>
        public static string ToggleIsPhotoListView {
            get {
                return ResourceManager.GetString("ToggleIsPhotoListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Character.
        /// </summary>
        public static string ToolCharacter {
            get {
                return ResourceManager.GetString("ToolCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TrayMenuAbout {
            get {
                return ResourceManager.GetString("TrayMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard History(Alt+Shift+S).
        /// </summary>
        public static string TrayMenuClipboardHistory {
            get {
                return ResourceManager.GetString("TrayMenuClipboardHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string TrayMenuHelp {
            get {
                return ResourceManager.GetString("TrayMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string TrayMenuOpen {
            get {
                return ResourceManager.GetString("TrayMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Ask(Alt+Shift+A).
        /// </summary>
        public static string TrayMenuQuickAsk {
            get {
                return ResourceManager.GetString("TrayMenuQuickAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string TrayMenuQuit {
            get {
                return ResourceManager.GetString("TrayMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Appliacation.
        /// </summary>
        public static string TrayMenuQuitTips {
            get {
                return ResourceManager.GetString("TrayMenuQuitTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Capture(Alt+Shift+Z).
        /// </summary>
        public static string TrayMenuScreenCapture {
            get {
                return ResourceManager.GetString("TrayMenuScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation(Alt+Shift+Q).
        /// </summary>
        public static string TrayMenuTranslateHistory {
            get {
                return ResourceManager.GetString("TrayMenuTranslateHistory", resourceCulture);
            }
        }
    }
}
